### ISSUE TITLE
Pip installing can't install the required packages

### ISSUE THREAD

**Issue by DueViktor** [loretoparisi/lshash#5]
I see that the this issue has occurred before and tried to fix with c29e127053694d8c055d4fca36617f5d38bc5383, but don't work. I would recommend using [poetry](https://python-poetry.org) or static dependencies.

```bash
Collecting lshashpy3
  Downloading lshashpy3-0.0.8.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ds/rtdqdzb153306j602rcl9s740000gn/T/pip-install-gzk7zag1/lshashpy3_4fd763b4e79d4694a442efe6e39318d4/setup.py", line 3, in <module>
          import lshashpy3
        File "/private/var/folders/ds/rtdqdzb153306j602rcl9s740000gn/T/pip-install-gzk7zag1/lshashpy3_4fd763b4e79d4694a442efe6e39318d4/lshashpy3/__init__.py", line 5, in <module>
          from .lshash import *
        File "/private/var/folders/ds/rtdqdzb153306j602rcl9s740000gn/T/pip-install-gzk7zag1/lshashpy3_4fd763b4e79d4694a442efe6e39318d4/lshashpy3/lshash.py", line 9, in <module>
          from future import standard_library
      ModuleNotFoundError: No module named 'future'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Th3OnlyN00b** [comment]
Did this ever get a fix?

**Comment by loretoparisi** [comment]
Updated `v0.0.9` to Pypi.

```
sh-4.2$ pip install --no-cache-dir lshashpy3
Collecting lshashpy3
  Downloading lshashpy3-0.0.9.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: future in ./anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/future-0.18.3-py3.10.egg (from lshashpy3) (0.18.3)
Requirement already satisfied: six in ./anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from lshashpy3) (1.16.0)
Requirement already satisfied: numpy in ./anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from lshashpy3) (1.26.0)
Requirement already satisfied: bitarray in ./anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitarray-2.8.4-py3.10-linux-x86_64.egg (from lshashpy3) (2.8.4)
Building wheels for collected packages: lshashpy3
  Building wheel for lshashpy3 (setup.py) ... done
  Created wheel for lshashpy3: filename=lshashpy3-0.0.9-py3-none-any.whl size=8875 sha256=8a2f8470331fbb47bc600c89a14215a1f270ad76688e7a499e26bcc986c478d1
  Stored in directory: /tmp/pip-ephem-wheel-cache-n60pqgb5/wheels/5f/f0/83/666c2757c9fbd2d87814f40a5fc3444d3a81cf8f6a912e4321
Successfully built lshashpy3
Installing collected packages: lshashpy3
Successfully installed lshashpy3-0.0.9
```
